#!/usr/bin/env python3
import os.path
import os
import sipconfig

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "config.sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
os.system(" ".join([config.sip_bin, "-c", ".", "-b", build_file, "kenlm-bindings.sip"]))

# Create the Makefile.
# Installation path is within the project, not central (DEST_DIR won't work correctly)
makefile = sipconfig.SIPModuleMakefile(config, build_file, install_dir=os.path.abspath("../../../bin/kenlm-bindings"))

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_libs = ["z"]


makefile.extra_include_dirs = [os.path.abspath("../../cpp/kenlm-wrapper"), os.path.abspath("../../../libs/kenlm")]
makefile.extra_lflags = ["../../../bin/kenlm-wrapper/kenlm-wrapper.o"]


# Generate the Makefile itself.
makefile.generate()
