/*
 * Internal module API header file.
 *
 * Generated by SIP 4.12.4 on Wed Dec 14 00:36:35 2011
 */

#ifndef _containerAPI_H
#define _containerAPI_H


#include <sip.h>

/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_disposeContainer 0
#define sipName_disposeContainer &sipStrings_container[0]
#define sipNameNr_updateContainer 17
#define sipName_updateContainer &sipStrings_container[17]
#define sipNameNr_createContainer 33
#define sipName_createContainer &sipStrings_container[33]
#define sipNameNr_containerInfo 49
#define sipName_containerInfo &sipStrings_container[49]
#define sipNameNr_FooContainer 63
#define sipName_FooContainer &sipStrings_container[63]
#define sipNameNr_container 76
#define sipName_container &sipStrings_container[76]
#define sipNameNr_members 86
#define sipName_members &sipStrings_container[86]

#define sipMalloc                   sipAPI_container->api_malloc
#define sipFree                     sipAPI_container->api_free
#define sipBuildResult              sipAPI_container->api_build_result
#define sipCallMethod               sipAPI_container->api_call_method
#define sipParseResult              sipAPI_container->api_parse_result
#define sipParseArgs                sipAPI_container->api_parse_args
#define sipParseKwdArgs             sipAPI_container->api_parse_kwd_args
#define sipParsePair                sipAPI_container->api_parse_pair
#define sipCommonDtor               sipAPI_container->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_container->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_container->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_container->api_convert_to_void_ptr
#define sipAddException             sipAPI_container->api_add_exception
#define sipNoFunction               sipAPI_container->api_no_function
#define sipNoMethod                 sipAPI_container->api_no_method
#define sipAbstractMethod           sipAPI_container->api_abstract_method
#define sipBadClass                 sipAPI_container->api_bad_class
#define sipBadCatcherResult         sipAPI_container->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_container->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_container->api_bad_operator_arg
#define sipTrace                    sipAPI_container->api_trace
#define sipTransferBack             sipAPI_container->api_transfer_back
#define sipTransferTo               sipAPI_container->api_transfer_to
#define sipTransferBreak            sipAPI_container->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_container->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_container->api_wrapper_type
#define sipWrapperType_Type         sipAPI_container->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_container->api_voidptr_type
#define sipGetPyObject              sipAPI_container->api_get_pyobject
#define sipGetAddress               sipAPI_container->api_get_address
#define sipGetCppPtr                sipAPI_container->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_container->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_container->api_is_py_method
#define sipCallHook                 sipAPI_container->api_call_hook
#define sipStartThread              sipAPI_container->api_start_thread
#define sipEndThread                sipAPI_container->api_end_thread
#define sipConnectRx                sipAPI_container->api_connect_rx
#define sipDisconnectRx             sipAPI_container->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_container->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_container->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_container->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_container->api_add_type_instance
#define sipFreeSipslot              sipAPI_container->api_free_sipslot
#define sipSameSlot                 sipAPI_container->api_same_slot
#define sipPySlotExtend             sipAPI_container->api_pyslot_extend
#define sipConvertRx                sipAPI_container->api_convert_rx
#define sipAddDelayedDtor           sipAPI_container->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_container->api_can_convert_to_type
#define sipConvertToType            sipAPI_container->api_convert_to_type
#define sipForceConvertToType       sipAPI_container->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_container->api_can_convert_to_enum
#define sipReleaseType              sipAPI_container->api_release_type
#define sipConvertFromType          sipAPI_container->api_convert_from_type
#define sipConvertFromNewType       sipAPI_container->api_convert_from_new_type
#define sipConvertFromEnum          sipAPI_container->api_convert_from_enum
#define sipGetState                 sipAPI_container->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_container->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_container->api_export_symbol
#define sipImportSymbol             sipAPI_container->api_import_symbol
#define sipFindType                 sipAPI_container->api_find_type
#define sipFindNamedEnum            sipAPI_container->api_find_named_enum
#define sipBytes_AsChar             sipAPI_container->api_bytes_as_char
#define sipBytes_AsString           sipAPI_container->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_container->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_container->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_container->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_container->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_container->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_container->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_container->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_container->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_container->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_container->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_container->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_container->api_invoke_slot
#define sipSaveSlot                 sipAPI_container->api_save_slot
#define sipClearAnySlotReference    sipAPI_container->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_container->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->type->td_cname)
#define sipDeprecated               sipAPI_container->api_deprecated
#define sipKeepReference            sipAPI_container->api_keep_reference
#define sipRegisterPyType           sipAPI_container->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_container->api_type_from_py_type_object
#define sipTypeScope                sipAPI_container->api_type_scope
#define sipResolveTypedef           sipAPI_container->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_container->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_container->api_is_api_enabled
#define sipExportModule             sipAPI_container->api_export_module
#define sipInitModule               sipAPI_container->api_init_module

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_container->api_map_string_to_class
#define sipMapIntToClass            sipAPI_container->api_map_int_to_class
#define sipFindClass                sipAPI_container->api_find_class
#define sipFindMappedType           sipAPI_container->api_find_mapped_type
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_container->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->type)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->type, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->type, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->type, (t))

/* The strings used by this module. */
extern const char sipStrings_container[];

#define sipType_FooContainer              sipModuleAPI_container.em_types[0]
#define sipClass_FooContainer             sipModuleAPI_container.em_types[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_container_FooContainer;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_container;
extern sipExportedModuleDef sipModuleAPI_container;

#endif
